package com.templeregistry.service.finance.pipeline;

import java.time.LocalDate;
import java.time.Month;

/**
 * The Indian financial year a business date falls in, in canonical form (FIN-055).
 *
 * <p>{@code fin_revenue_fact.financial_year} is stored rather than generated by the database,
 * so it is functionally dependent on a column sitting beside it. A loader that computes it
 * with the wrong year start produces facts that disagree with their own dates, and nothing
 * downstream can detect that: both columns look plausible in isolation. This class is the one
 * place the computation lives.
 *
 * <p>The year runs 1 April to 31 March, which is statutory for Indian government accounting
 * and not a per-temple preference. A temple whose internal books ran on some other cycle would
 * still be reported to the department on this one.
 *
 * <p>The string form is {@code 2025-26}, never {@code 20252026} and never {@code 2025-2026}:
 * it is compared and grouped as text throughout the reporting layer, so one spelling has to
 * win. The second part is the last two digits of the following year, which is why a year
 * ending in 2100 renders as {@code 2099-00} — correct, and the conventional rendering.
 */
public final class FinancialYear {

    /** First month of the financial year. Statutory, not configuration. */
    static final Month START_MONTH = Month.APRIL;

    private FinancialYear() {
    }

    /**
     * The financial year containing {@code businessDate}.
     *
     * @param businessDate the date the revenue belongs to financially — never an extraction
     *                     or modification date (FIN-D-012)
     * @return canonical form, e.g. {@code 2025-26}
     * @throws IllegalArgumentException if the date is null, which is a caller defect: a fact
     *                                  with no business date must be rejected before it gets here
     */
    public static String of(LocalDate businessDate) {
        if (businessDate == null) {
            throw new IllegalArgumentException("A financial year cannot be derived from no date");
        }
        int startYear = businessDate.getMonthValue() >= START_MONTH.getValue()
                ? businessDate.getYear()
                : businessDate.getYear() - 1;
        return "%d-%02d".formatted(startYear, (startYear + 1) % 100);
    }

    /**
     * First day of a canonical financial year (FIN-060).
     *
     * <p>Reconciliation asks a source to total a business-date range, and that range has to be
     * derived from the same definition that put the facts in the year. Computing 1 April in the
     * reconciler would be a second place the year start lives, which is the defect this class
     * exists to prevent.
     *
     * @throws IllegalArgumentException if the string is not canonical form
     */
    public static LocalDate startOf(String financialYear) {
        return LocalDate.of(startYearOf(financialYear), START_MONTH, 1);
    }

    /** Last day of a canonical financial year — inclusive, and leap-year correct. */
    public static LocalDate endOf(String financialYear) {
        return startOf(financialYear).plusYears(1).minusDays(1);
    }

    /**
     * Whether the year has finished as of {@code asOf}.
     *
     * <p>Load-bearing for FIN-060: a shortfall in an <em>open</em> year is not evidence of
     * anything, because records may still arrive. Only a closed year makes a shortfall worth
     * recording as a suspicion at all.
     */
    public static boolean isClosed(String financialYear, LocalDate asOf) {
        return asOf.isAfter(endOf(financialYear));
    }

    /**
     * Parses the leading year, rejecting anything that is not canonical form.
     *
     * <p>Strict on purpose. {@code 2025-2026} and {@code 2025} would both parse "well enough" to
     * produce a date, and a reconciliation range silently built from a misread year would compare
     * the wrong twelve months and report a variance nobody could explain.
     */
    private static int startYearOf(String financialYear) {
        if (financialYear == null || financialYear.length() != 7 || financialYear.charAt(4) != '-') {
            throw new IllegalArgumentException(
                    "Not a canonical financial year: " + financialYear + ". Expected yyyy-yy.");
        }
        try {
            int startYear = Integer.parseInt(financialYear.substring(0, 4));
            int endYear = Integer.parseInt(financialYear.substring(5));
            if (endYear != (startYear + 1) % 100) {
                throw new IllegalArgumentException(
                        "Financial year " + financialYear + " does not end in the year after it "
                                + "starts; one half of it is wrong and there is no way to tell "
                                + "which.");
            }
            return startYear;
        } catch (NumberFormatException notNumeric) {
            throw new IllegalArgumentException(
                    "Not a canonical financial year: " + financialYear + ". Expected yyyy-yy.",
                    notNumeric);
        }
    }
}
