package com.templeregistry.service.finance.pipeline;

import java.time.LocalDate;
import java.time.Month;

/**
 * The Indian financial year a business date falls in, in canonical form (FIN-055).
 *
 * <p>{@code fin_revenue_fact.financial_year} is stored rather than generated by the database,
 * so it is functionally dependent on a column sitting beside it. A loader that computes it
 * with the wrong year start produces facts that disagree with their own dates, and nothing
 * downstream can detect that: both columns look plausible in isolation. This class is the one
 * place the computation lives.
 *
 * <p>The year runs 1 April to 31 March, which is statutory for Indian government accounting
 * and not a per-temple preference. A temple whose internal books ran on some other cycle would
 * still be reported to the department on this one.
 *
 * <p>The string form is {@code 2025-26}, never {@code 20252026} and never {@code 2025-2026}:
 * it is compared and grouped as text throughout the reporting layer, so one spelling has to
 * win. The second part is the last two digits of the following year, which is why a year
 * ending in 2100 renders as {@code 2099-00} — correct, and the conventional rendering.
 */
public final class FinancialYear {

    /** First month of the financial year. Statutory, not configuration. */
    static final Month START_MONTH = Month.APRIL;

    private FinancialYear() {
    }

    /**
     * The financial year containing {@code businessDate}.
     *
     * @param businessDate the date the revenue belongs to financially — never an extraction
     *                     or modification date (FIN-D-012)
     * @return canonical form, e.g. {@code 2025-26}
     * @throws IllegalArgumentException if the date is null, which is a caller defect: a fact
     *                                  with no business date must be rejected before it gets here
     */
    public static String of(LocalDate businessDate) {
        if (businessDate == null) {
            throw new IllegalArgumentException("A financial year cannot be derived from no date");
        }
        int startYear = businessDate.getMonthValue() >= START_MONTH.getValue()
                ? businessDate.getYear()
                : businessDate.getYear() - 1;
        return "%d-%02d".formatted(startYear, (startYear + 1) % 100);
    }
}
