-- ============================================================================
-- V10: Temple Seed Data — 20 Real Karnataka Temples
-- Full workflow coverage: Trust · Declaration · Profile · WorkflowInstance
--                         · WorkflowTransition history · DC users all districts
-- IDEMPOTENT: all inserts use INSERT IGNORE.
-- ============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- ── ENCRYPTED VALUES ─────────────────────────────────────────────────────────
-- AES-256-GCM, dev key: TempleRegDev32ByteKey!!Replace!!
-- Generated by backend/EncryptSeedValues.java (that file can be deleted now).

SET @ph          = '$2a$12$Jh5AwLDdLLbuS.Otkb0AK.2aFveu2vjEBCOYKEDKEYk757A2yNrQS';  -- password123

-- Trust PANs (plaintext format AABCS####Z)
SET @PAN_T01  = 'QUFCQ1MxMDAxWgAATRSrLLowwG5tWij4kkiTbxwNUgLt+qxwAWM=';
SET @PAN_T02  = 'QUFCQ1MxMDAyWgAAg6QeSMeCiQoN3FG2GauWA6AbLRNnqeALO/E=';
SET @PAN_T03  = 'QUFCQ1MxMDAzWgAAAOQKYg6uUc9KeOF6ae2tA+geDyGyao/soZ8=';
SET @PAN_T04  = 'QUFCQ1MxMDA0WgAAMap5kazhs0iBoT/aJfQuGFRGHyOqvp0MnjQ=';
SET @PAN_T05  = 'QUFCQ1MxMDA1WgAA9Lxy4lP5OjS3EKSIuu6EVYtjgIys/l/EL/Q=';
SET @PAN_T06  = 'QUFCQ1MxMDA2WgAADgEio4Q02WcqT13/jziNELHv2ljuil9I6fw=';
SET @PAN_T07  = 'QUFCQ1MxMDA3WgAAnoy27BGDVw/t1rWbSx56tKAu35QxefH5ocE=';
SET @PAN_T08  = 'QUFCQ1MxMDA4WgAAMgsWGzwfjicdV3KoNYh8A15O0nwoq+1VEhI=';
SET @PAN_T09  = 'QUFCQ1MxMDA5WgAArSkMCpdyt+pw66R0PhW981vLQYXT+6+GVOg=';
SET @PAN_T10  = 'QUFCQ1MxMDEwWgAApfKA9Q2H72Ezk45PZO0C+ynGvpJoAvzuOzM=';
SET @PAN_T11  = 'QUFCQ1MxMDExWgAAV2ONg/5KGu0xu4BylfTWXwOUgiybVjLQrwc=';
SET @PAN_T12  = 'QUFCQ1MxMDEyWgAAil2b5MZk7fzyNMBm/iusqvmYVAhpsnOCnPQ=';
SET @PAN_T13  = 'QUFCQ1MxMDEzWgAAc+ZLoyRE8TYwsZnJseMXF8kgwZZ+5CyVd78=';
SET @PAN_T15  = 'QUFCQ1MxMDE1WgAAuUBsb24C860CWyfzgTdmOZR2b3oPWv+DERs=';
SET @PAN_T19  = 'QUFCQ1MxMDE5WgAADzkzLgIE+UVdfzNLQlaQFUIaHAZAP0RyBRs=';
SET @PAN_T20  = 'QUFCQ1MxMDIwWgAA4qTYMoomZGdRiTYzMxZ1TOXGueoOiNy7Yx4=';

-- Trust bank accounts (AES-GCM encrypted)
SET @BANK_T01 = 'MTAwMTAwMTAwMTAAQuW9w1Kdg74vuwddrC01+vhM9mV1RGLzub9T';
SET @BANK_T02 = 'MTAwMjAwMjAwMjAA7ceesukMiyTIUHatMvJlCzcSGzTnQFysAp/n';
SET @BANK_T03 = 'MTAwMzAwMzAwMzAAtXWp3+LfEllGYcfHfpy/UaoOoE7GWMRLTR18';
SET @BANK_T04 = 'MTAwNDAwNDAwNDAAJsdQlnAFivv6wr90ZqdcQdJ5/aDkHMs+QERq';
SET @BANK_T05 = 'MTAwNTAwNTAwNTAAEo6FRONeHM8RsiIEU6BVggwE5JP6mXLybjoc';
SET @BANK_T06 = 'MTAwNjAwNjAwNjAAe5RfBfZUWn9kQpmlprVGb0XZYjkxf4EG4NBA';
SET @BANK_T07 = 'MTAwNzAwNzAwNzAAVJtdG6yArUxEeJa4Jd1hcw4BlvAmyoG6tVe8';
SET @BANK_T08 = 'MTAwODAwODAwODAAc4Sky5QHo1ljogh2cSDGAH6UD/mzjKQ5/eWf';
SET @BANK_T09 = 'MTAwOTAwOTAwOTAAujUu1SzpHW6cpdEyzjIR4RrTNxPhPYUCdYLk';
SET @BANK_T10 = 'MTAxMDAxMDAxMDAA4xBXIr5IxEiydFTm6WvBgCThq+lK68fwHkJa';
SET @BANK_T11 = 'MTAxMTAxMTAxMTAAcZ77bTBtubpNg+w2CsqhkvmAePQM+9iSjILn';
SET @BANK_T12 = 'MTAxMjAxMjAxMjAARFbU4swf4WWbY7E9NZ2smESNjvktapRnsx/v';
SET @BANK_T13 = 'MTAxMzAxMzAxMzAAgN/7QifPH+5LCquym9k5XtaC+mY/D/j0/1F8';
SET @BANK_T15 = 'MTAxNTAxNTAxNTAAElpVlpYfGQN8io3SBjTnA5I1qCRrp81kfWRa';
SET @BANK_T19 = 'MTAxOTAxOTAxOTAANYaGc+N/jSCZYjPN49a8RB4XKcZ16Gfg5JZz';
SET @BANK_T20 = 'MTAyMDAyMDAyMDAAAXjauuyqLQhFNtYOzEoRHry+GW9EuYlUo8ZE';

-- Profile staging bank accounts (AES-GCM encrypted)
SET @PROF_BANK_T01 = 'MjAwMTAwMTAwMTAA/6cqb727fZ7xfhi5K5XfOloYg/XGqEDmVGO9';
SET @PROF_BANK_T03 = 'MjAwMzAwMzAwMzAAS9AMJBdYt+WamUyUBC0POKVMNkWVoC49fElh';
SET @PROF_BANK_T06 = 'MjAwNjAwNjAwNjAA3bLWlsE9H2v+WrgzRbyqjDzB5UBS+M1P0eTb';


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 1 — DC USERS FOR ALL 20 DISTRICTS
-- Existing: id=2 dc_mysuru (district=1) · id=7 dc_bengaluru (district=6)
-- New: districts 2-5 and 7-20 → ids 120-137
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO users
    (id, username, email, password_hash, full_name, mobile, role, is_active,
     district_id, city_id, temple_id, designation, access_type, is_deleted, created_by)
VALUES
    (120,'dc_mandya','dc_mandya@templeregistry.dev',@ph,'District Collector, Mandya',
     '9876500120','DISTRICT_COLLECTOR',1,2,1,NULL,'District Collector','EDIT',0,1),
    (121,'dc_chamarajanagar','dc_chamarajanagar@templeregistry.dev',@ph,'District Collector, Chamarajanagar',
     '9876500121','DISTRICT_COLLECTOR',1,3,1,NULL,'District Collector','EDIT',0,1),
    (122,'dc_kodagu','dc_kodagu@templeregistry.dev',@ph,'District Collector, Kodagu',
     '9876500122','DISTRICT_COLLECTOR',1,4,1,NULL,'District Collector','EDIT',0,1),
    (123,'dc_hassan','dc_hassan@templeregistry.dev',@ph,'District Collector, Hassan',
     '9876500123','DISTRICT_COLLECTOR',1,5,1,NULL,'District Collector','EDIT',0,1),
    (124,'dc_bengaluru_rural','dc_bengaluru_rural@templeregistry.dev',@ph,'District Collector, Bengaluru Rural',
     '9876500124','DISTRICT_COLLECTOR',1,7,2,NULL,'District Collector','EDIT',0,1),
    (125,'dc_ramanagara','dc_ramanagara@templeregistry.dev',@ph,'District Collector, Ramanagara',
     '9876500125','DISTRICT_COLLECTOR',1,8,2,NULL,'District Collector','EDIT',0,1),
    (126,'dc_tumkuru','dc_tumkuru@templeregistry.dev',@ph,'District Collector, Tumkuru',
     '9876500126','DISTRICT_COLLECTOR',1,9,2,NULL,'District Collector','EDIT',0,1),
    (127,'dc_kolar','dc_kolar@templeregistry.dev',@ph,'District Collector, Kolar',
     '9876500127','DISTRICT_COLLECTOR',1,10,2,NULL,'District Collector','EDIT',0,1),
    (128,'dc_kalaburagi','dc_kalaburagi@templeregistry.dev',@ph,'District Collector, Kalaburagi',
     '9876500128','DISTRICT_COLLECTOR',1,11,3,NULL,'District Collector','EDIT',0,1),
    (129,'dc_bidar','dc_bidar@templeregistry.dev',@ph,'District Collector, Bidar',
     '9876500129','DISTRICT_COLLECTOR',1,12,3,NULL,'District Collector','EDIT',0,1),
    (130,'dc_raichur','dc_raichur@templeregistry.dev',@ph,'District Collector, Raichur',
     '9876500130','DISTRICT_COLLECTOR',1,13,3,NULL,'District Collector','EDIT',0,1),
    (131,'dc_belagavi','dc_belagavi@templeregistry.dev',@ph,'District Collector, Belagavi',
     '9876500131','DISTRICT_COLLECTOR',1,14,4,NULL,'District Collector','EDIT',0,1),
    (132,'dc_vijayapura','dc_vijayapura@templeregistry.dev',@ph,'District Collector, Vijayapura',
     '9876500132','DISTRICT_COLLECTOR',1,15,4,NULL,'District Collector','EDIT',0,1),
    (133,'dc_bagalkot','dc_bagalkot@templeregistry.dev',@ph,'District Collector, Bagalkot',
     '9876500133','DISTRICT_COLLECTOR',1,16,4,NULL,'District Collector','EDIT',0,1),
    (134,'dc_dharwad','dc_dharwad@templeregistry.dev',@ph,'District Collector, Dharwad',
     '9876500134','DISTRICT_COLLECTOR',1,17,4,NULL,'District Collector','EDIT',0,1),
    (135,'dc_shivamogga','dc_shivamogga@templeregistry.dev',@ph,'District Collector, Shivamogga',
     '9876500135','DISTRICT_COLLECTOR',1,18,5,NULL,'District Collector','EDIT',0,1),
    (136,'dc_davanagere','dc_davanagere@templeregistry.dev',@ph,'District Collector, Davanagere',
     '9876500136','DISTRICT_COLLECTOR',1,19,5,NULL,'District Collector','EDIT',0,1),
    (137,'dc_chitradurga','dc_chitradurga@templeregistry.dev',@ph,'District Collector, Chitradurga',
     '9876500137','DISTRICT_COLLECTOR',1,20,5,NULL,'District Collector','EDIT',0,1);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 2 — TEMPLES (ids 100-119)
-- Inserted BEFORE TA users to satisfy FK fk_users_temple (V3 migration).
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO temples
    (id, version, registration_number, name, grade, primary_deity, tradition,
     year_established, hobli_id, taluk_id, city_id, district_id,
     latitude, longitude,
     contact_name, contact_designation, contact_mobile,
     bank_name, bank_ifsc,
     trust_registered, asset_declaration_status, status, verification_status,
     is_deleted, created_by)
VALUES
    -- T01: Sri Chamundeshwari Temple · Mysuru · Grade A · SHAKTA · ACTIVE
    (100,0,'KA-MYS-0001','Sri Chamundeshwari Temple','A','Chamundeshwari','SHAKTA',
     1659,1,1,1,1,12.2723000,76.6722000,
     'Executive Officer','Temple Authority','9900000100',
     'State Bank of India','SBIN0040001',
     1,'APPROVED','ACTIVE','VERIFIED',0,1),
    -- T02: Sri Nanjundeshwara Temple · Mysuru · Grade A · SHAIVITE · ACTIVE
    (101,0,'KA-MYS-0002','Sri Nanjundeshwara Temple','A','Nanjundeshwara','SHAIVITE',
     1143,2,1,1,1,12.1220000,76.6836000,
     'Executive Officer','Temple Authority','9900000101',
     NULL,NULL,
     1,'APPROVED','ACTIVE','VERIFIED',0,1),
    -- T03: Sri Ranganathaswamy Temple · Mandya · Grade A · VAISHNAVITE · ACTIVE
    (102,0,'KA-MDY-0001','Sri Ranganathaswamy Temple','A','Ranganathaswamy','VAISHNAVITE',
     894,5,4,1,2,12.4188000,76.6942000,
     'Executive Officer','Temple Authority','9900000102',
     NULL,NULL,
     1,'APPROVED','ACTIVE','VERIFIED',0,1),
    -- T04: Sri Mahadeshwara Temple · Chamarajanagar · Grade A · SHAIVITE · OVERDUE decl
    (103,0,'KA-CJN-0001','Sri Mahadeshwara Temple','A','Mahadeshwara','SHAIVITE',
     1310,7,7,1,3,11.7725000,77.0047000,
     'Executive Officer','Temple Authority','9900000103',
     NULL,NULL,
     0,'OVERDUE','ACTIVE','UNVERIFIED',0,1),
    -- T05: Sri Omkareshwara Temple · Kodagu · Grade B · SHAIVITE · UNDER_REVIEW decl
    (104,0,'KA-KDG-0001','Sri Omkareshwara Temple','B','Omkareshwara','SHAIVITE',
     1820,8,9,1,4,12.4251000,75.7427000,
     'Executive Officer','Temple Authority','9900000104',
     NULL,NULL,
     1,'UNDER_REVIEW','ACTIVE','UNVERIFIED',0,1),
    -- T06: Hoysaleshwara Temple · Hassan · Grade A · SHAIVITE · CLARIFICATION_REQUIRED decl
    (105,0,'KA-HSN-0001','Hoysaleshwara Temple','A','Hoysaleshwara','SHAIVITE',
     1121,9,11,1,5,13.2164000,76.0148000,
     'Executive Officer','Temple Authority','9900000105',
     NULL,NULL,
     1,'CLARIFICATION_REQUIRED','ACTIVE','UNVERIFIED',0,1),
    -- T07: Sri Chennakesava Temple · Hassan · Grade B · VAISHNAVITE · SITE_VISIT_SCHEDULED decl
    (106,0,'KA-HSN-0002','Sri Chennakesava Temple','B','Chennakesava','VAISHNAVITE',
     1117,9,12,1,5,13.1593000,75.8643000,
     'Executive Officer','Temple Authority','9900000106',
     NULL,NULL,
     1,'SITE_VISIT_SCHEDULED','ACTIVE','UNVERIFIED',0,1),
    -- T08: Sri Kadu Malleshwara Temple · Bengaluru Urban · Grade B · SHAIVITE · SITE_VISIT_COMPLETED decl
    (107,0,'KA-BLR-0001','Sri Kadu Malleshwara Temple','B','Kadu Malleshwara','SHAIVITE',
     1800,10,13,2,6,13.0035000,77.5700000,
     'Executive Officer','Temple Authority','9900000107',
     NULL,NULL,
     0,'SITE_VISIT_COMPLETED','ACTIVE','UNVERIFIED',0,1),
    -- T09: Sri Gangadhareshwara Cave Temple · Bengaluru Urban · Grade B · SHAIVITE · SUBMITTED decl
    (108,0,'KA-BLR-0002','Sri Gangadhareshwara Cave Temple','B','Gangadhareshwara','SHAIVITE',
     1537,11,14,2,6,12.9400000,77.5700000,
     'Executive Officer','Temple Authority','9900000108',
     NULL,NULL,
     0,'SUBMITTED','ACTIVE','UNVERIFIED',0,1),
    -- T10: ISKCON Sri Radha Krishnachandra Temple · Bengaluru Urban · Grade A · VAISHNAVITE · VERIFIED decl
    (109,0,'KA-BLR-0003','ISKCON Sri Radha Krishnachandra Temple','A','Radha Krishnachandra','VAISHNAVITE',
     1997,10,13,2,6,13.0130000,77.5523000,
     'Executive Officer','Temple Authority','9900000109',
     NULL,NULL,
     1,'VERIFIED','ACTIVE','UNVERIFIED',0,1),
    -- T11: Sri Siddaganga Mutt Temple · Tumkuru · Grade A · SHAIVITE · APPROVED decl (v2)
    (110,0,'KA-TMK-0001','Sri Siddaganga Mutt Temple','A','Siddagangaiah Swami','SHAIVITE',
     1399,12,16,2,9,13.3465000,77.0840000,
     'Executive Officer','Temple Authority','9900000110',
     NULL,NULL,
     1,'APPROVED','ACTIVE','VERIFIED',0,1),
    -- T12: Sri Siddaroodha Swami Temple · Dharwad · Grade B · SHAIVITE · DRAFT decl (after rejection)
    (111,0,'KA-DWD-0001','Sri Siddaroodha Swami Temple','B','Siddaroodha Swami','SHAIVITE',
     1907,13,18,4,17,15.3350000,75.1240000,
     'Executive Officer','Temple Authority','9900000111',
     NULL,NULL,
     1,'DRAFT','ACTIVE','UNVERIFIED',0,1),
    -- T13: Sri Keladi Rameshwara Temple · Shivamogga · Grade B · SHAIVITE · no declaration
    (112,0,'KA-SHV-0001','Sri Keladi Rameshwara Temple','B','Rameshwara','SHAIVITE',
     1580,14,20,5,18,14.0478000,75.0193000,
     'Executive Officer','Temple Authority','9900000112',
     NULL,NULL,
     1,NULL,'ACTIVE','UNVERIFIED',0,1),
    -- T14: Sri Tarakeshwara Temple · Davanagere · Grade C · SHAIVITE · DRAFT decl
    (113,0,'KA-DVG-0001','Sri Tarakeshwara Temple','C','Tarakeshwara','SHAIVITE',
     1380,NULL,NULL,5,19,NULL,NULL,
     'Executive Officer','Temple Authority','9900000113',
     NULL,NULL,
     0,'DRAFT','ACTIVE','UNVERIFIED',0,1),
    -- T15: Sri Sharana Basaveshwara Temple · Kalaburagi · Grade B · SHAIVITE · SUSPENDED · APPROVED decl
    (114,0,'KA-KLB-0001','Sri Sharana Basaveshwara Temple','B','Sharana Basaveshwara','SHAIVITE',
     1649,NULL,NULL,3,11,NULL,NULL,
     'Executive Officer','Temple Authority','9900000114',
     NULL,NULL,
     1,'APPROVED','SUSPENDED','UNVERIFIED',0,1),
    -- T16: Sri Ucchangi Bhairaveshwara Temple · Chitradurga · Grade C · SHAKTA · WITHDRAWN decl
    (115,0,'KA-CTD-0001','Sri Ucchangi Bhairaveshwara Temple','C','Bhairaveshwara','SHAKTA',
     1050,NULL,NULL,5,20,NULL,NULL,
     'Executive Officer','Temple Authority','9900000115',
     NULL,NULL,
     0,'WITHDRAWN','ACTIVE','UNVERIFIED',0,1),
    -- T17: Sri Gurudwara Nanak Jhira Sahib · Bidar · Grade B · OTHER · no declaration
    (116,0,'KA-BDR-0001','Sri Gurudwara Nanak Jhira Sahib','B','Guru Nanak','OTHER',
     1499,NULL,NULL,3,12,NULL,NULL,
     'Executive Officer','Temple Authority','9900000116',
     NULL,NULL,
     0,NULL,'ACTIVE','UNVERIFIED',0,1),
    -- T18: Sri Manavi Veerbhadreshwara Temple · Raichur · Grade C · SHAIVITE · FROZEN
    (117,0,'KA-RCR-0001','Sri Manavi Veerbhadreshwara Temple','C','Veerbhadreshwara','SHAIVITE',
     1200,NULL,NULL,3,13,NULL,NULL,
     'Executive Officer','Temple Authority','9900000117',
     NULL,NULL,
     0,NULL,'FROZEN','UNVERIFIED',0,1),
    -- T19: Sri Balagangadharanatha Temple · Bengaluru Rural · Grade C · SHAIVITE · SUBMITTED decl (v2)
    (118,0,'KA-BLR-0004','Sri Balagangadharanatha Temple','C','Balagangadharanatha','SHAIVITE',
     1760,NULL,NULL,2,7,NULL,NULL,
     'Executive Officer','Temple Authority','9900000118',
     NULL,NULL,
     0,'SUBMITTED','ACTIVE','UNVERIFIED',0,1),
    -- T20: Sri Kambadahalli Bahubali Temple · Mandya · Grade C · JAIN · ARCHIVED
    (119,0,'KA-MDY-0002','Sri Kambadahalli Bahubali Temple','C','Bahubali','JAIN',
     900,6,5,1,2,NULL,NULL,
     'Executive Officer','Temple Authority','9900000119',
     NULL,NULL,
     1,NULL,'ARCHIVED','UNVERIFIED',0,1);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 3 — TEMPLE AUTHORITY USERS (ids 100-119)
-- temple_id FK requires Section 2 temples to exist first.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO users
    (id, username, email, password_hash, full_name, mobile, role, is_active,
     district_id, city_id, temple_id, designation, access_type, is_deleted, created_by)
VALUES
    (100,'ta_chamundeshwari','ta_chamundeshwari@templeregistry.dev',@ph,
     'Temple Authority, Sri Chamundeshwari','9900100100','TEMPLE_AUTHORITY',1,1,1,100,'Executive Officer','EDIT',0,1),
    (101,'ta_nanjundeshwara','ta_nanjundeshwara@templeregistry.dev',@ph,
     'Temple Authority, Sri Nanjundeshwara','9900100101','TEMPLE_AUTHORITY',1,1,1,101,'Executive Officer','EDIT',0,1),
    (102,'ta_ranganathaswamy','ta_ranganathaswamy@templeregistry.dev',@ph,
     'Temple Authority, Sri Ranganathaswamy','9900100102','TEMPLE_AUTHORITY',1,2,1,102,'Executive Officer','EDIT',0,1),
    (103,'ta_mahadeshwara','ta_mahadeshwara@templeregistry.dev',@ph,
     'Temple Authority, Sri Mahadeshwara','9900100103','TEMPLE_AUTHORITY',1,3,1,103,'Executive Officer','EDIT',0,1),
    (104,'ta_omkareshwara','ta_omkareshwara@templeregistry.dev',@ph,
     'Temple Authority, Sri Omkareshwara','9900100104','TEMPLE_AUTHORITY',1,4,1,104,'Executive Officer','EDIT',0,1),
    (105,'ta_hoysaleshwara','ta_hoysaleshwara@templeregistry.dev',@ph,
     'Temple Authority, Hoysaleshwara','9900100105','TEMPLE_AUTHORITY',1,5,1,105,'Executive Officer','EDIT',0,1),
    (106,'ta_chennakesava','ta_chennakesava@templeregistry.dev',@ph,
     'Temple Authority, Sri Chennakesava','9900100106','TEMPLE_AUTHORITY',1,5,1,106,'Executive Officer','EDIT',0,1),
    (107,'ta_kadu_malleshwara','ta_kadu_malleshwara@templeregistry.dev',@ph,
     'Temple Authority, Sri Kadu Malleshwara','9900100107','TEMPLE_AUTHORITY',1,6,2,107,'Executive Officer','EDIT',0,1),
    (108,'ta_gangadhareshwara','ta_gangadhareshwara@templeregistry.dev',@ph,
     'Temple Authority, Sri Gangadhareshwara','9900100108','TEMPLE_AUTHORITY',1,6,2,108,'Executive Officer','EDIT',0,1),
    (109,'ta_iskcon','ta_iskcon@templeregistry.dev',@ph,
     'Temple Authority, ISKCON Bengaluru','9900100109','TEMPLE_AUTHORITY',1,6,2,109,'Executive Officer','EDIT',0,1),
    (110,'ta_siddaganga','ta_siddaganga@templeregistry.dev',@ph,
     'Temple Authority, Sri Siddaganga Mutt','9900100110','TEMPLE_AUTHORITY',1,9,2,110,'Executive Officer','EDIT',0,1),
    (111,'ta_siddaroodha','ta_siddaroodha@templeregistry.dev',@ph,
     'Temple Authority, Sri Siddaroodha Swami','9900100111','TEMPLE_AUTHORITY',1,17,4,111,'Executive Officer','EDIT',0,1),
    (112,'ta_keladi','ta_keladi@templeregistry.dev',@ph,
     'Temple Authority, Sri Keladi Rameshwara','9900100112','TEMPLE_AUTHORITY',1,18,5,112,'Executive Officer','EDIT',0,1),
    (113,'ta_tarakeshwara','ta_tarakeshwara@templeregistry.dev',@ph,
     'Temple Authority, Sri Tarakeshwara','9900100113','TEMPLE_AUTHORITY',1,19,5,113,'Executive Officer','EDIT',0,1),
    (114,'ta_basaveshwara','ta_basaveshwara@templeregistry.dev',@ph,
     'Temple Authority, Sri Sharana Basaveshwara','9900100114','TEMPLE_AUTHORITY',0,11,3,114,'Executive Officer','EDIT',0,1),
    (115,'ta_ucchangi','ta_ucchangi@templeregistry.dev',@ph,
     'Temple Authority, Sri Ucchangi Bhairaveshwara','9900100115','TEMPLE_AUTHORITY',1,20,5,115,'Executive Officer','EDIT',0,1),
    (116,'ta_nanak_jhira','ta_nanak_jhira@templeregistry.dev',@ph,
     'Temple Authority, Sri Gurudwara Nanak Jhira','9900100116','TEMPLE_AUTHORITY',1,12,3,116,'Executive Officer','EDIT',0,1),
    (117,'ta_manavi','ta_manavi@templeregistry.dev',@ph,
     'Temple Authority, Sri Manavi Veerbhadreshwara','9900100117','TEMPLE_AUTHORITY',0,13,3,117,'Executive Officer','EDIT',0,1),
    (118,'ta_balagangadharanatha','ta_balagangadharanatha@templeregistry.dev',@ph,
     'Temple Authority, Sri Balagangadharanatha','9900100118','TEMPLE_AUTHORITY',1,7,2,118,'Executive Officer','EDIT',0,1),
    (119,'ta_kambadahalli','ta_kambadahalli@templeregistry.dev',@ph,
     'Temple Authority, Sri Kambadahalli Bahubali','9900100119','TEMPLE_AUTHORITY',0,2,1,119,'Executive Officer','EDIT',0,1);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 4 — TRUSTS (ids 100-115)
-- 16 trusts covering APPROVED / SUBMITTED / CLARIFICATION_REQUESTED /
-- REJECTED / DRAFT / DISSOLVED workflow scenarios.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO trusts
    (id, lock_version, temple_id, trust_name, trust_registration_number,
     date_of_registration, registering_authority, trust_type,
     trust_pan_number, bank_account_number, bank_name_and_branch,
     annual_income, status, dissolution_date, dissolution_reason,
     system_verification_status, approved_data,
     is_deleted, created_by)
VALUES
    -- WF=APPROVED
    (100,0,100,'Sri Chamundeshwari Devasthana Trust','KA/MYS/TR/1987/001',
     '1987-04-15','Sub Registrar, Mysuru','MULTI_TRUSTEE',
     @PAN_T01,@BANK_T01,'State Bank of India, Chamundi Branch',
     9500000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Sri Chamundeshwari Devasthana Trust","trustType":"MULTI_TRUSTEE","trustRegistrationNumber":"KA/MYS/TR/1987/001","registeringAuthority":"Sub Registrar, Mysuru"}',
     0,100),
    (101,0,101,'Sri Nanjundeshwara Devasthana Trust','KA/MYS/TR/1992/002',
     '1992-06-20','Sub Registrar, Mysuru','MULTI_TRUSTEE',
     @PAN_T02,@BANK_T02,'Canara Bank, Nanjangud Branch',
     3500000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Sri Nanjundeshwara Devasthana Trust","trustType":"MULTI_TRUSTEE","trustRegistrationNumber":"KA/MYS/TR/1992/002","registeringAuthority":"Sub Registrar, Mysuru"}',
     0,101),
    (102,0,102,'Sri Ranganathaswamy Temple Trust','KA/MDY/TR/1985/001',
     '1985-03-10','Sub Registrar, Mandya','ENDOWMENT',
     @PAN_T03,@BANK_T03,'State Bank of India, Srirangapatna Branch',
     4200000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Sri Ranganathaswamy Temple Trust","trustType":"ENDOWMENT","trustRegistrationNumber":"KA/MDY/TR/1985/001","registeringAuthority":"Sub Registrar, Mandya"}',
     0,102),
    -- WF=SUBMITTED (trust not yet approved; temple.trust_registered=false)
    (103,0,103,'Sri Mahadeshwara Shivagange Trust','KA/CJN/TR/2001/001',
     '2001-08-12','Sub Registrar, Chamarajanagar','MULTI_TRUSTEE',
     @PAN_T04,@BANK_T04,'Karnataka Bank, MM Hills Branch',
     1200000.00,'ACTIVE',NULL,NULL,NULL,NULL,
     0,103),
    -- WF=APPROVED
    (104,0,104,'Kodagu Sri Omkareshwara Devasthana Trust','KA/KDG/TR/2005/001',
     '2005-11-20','Sub Registrar, Madikeri','SINGLE_TRUSTEE',
     @PAN_T05,@BANK_T05,'Corporation Bank, Madikeri Branch',
     850000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Kodagu Sri Omkareshwara Devasthana Trust","trustType":"SINGLE_TRUSTEE","trustRegistrationNumber":"KA/KDG/TR/2005/001","registeringAuthority":"Sub Registrar, Madikeri"}',
     0,104),
    -- WF=CLARIFICATION_REQUESTED (trust approved but needs clarification on edit)
    (105,0,105,'Halebidu Hoysaleshwara Heritage Trust','KA/HSN/TR/1975/001',
     '1975-07-01','Sub Registrar, Hassan','MULTI_TRUSTEE',
     @PAN_T06,@BANK_T06,'State Bank of India, Hassan Branch',
     2800000.00,'ACTIVE',NULL,NULL,NULL,NULL,
     0,105),
    -- WF=APPROVED
    (106,0,106,'Sri Chennakesava Temple Endowment Fund','KA/HSN/TR/1968/001',
     '1968-04-14','Sub Registrar, Hassan','ENDOWMENT',
     @PAN_T07,@BANK_T07,'Syndicate Bank, Belur Branch',
     1600000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Sri Chennakesava Temple Endowment Fund","trustType":"ENDOWMENT","trustRegistrationNumber":"KA/HSN/TR/1968/001","registeringAuthority":"Sub Registrar, Hassan"}',
     0,106),
    -- WF=REJECTED (trust rejected; temple.trust_registered=false)
    (107,0,107,'Malleshwaram Sri Kadu Malleshwara Trust','KA/BLR/TR/2010/001',
     '2010-01-15','Sub Registrar, Bengaluru Urban','MULTI_TRUSTEE',
     @PAN_T08,@BANK_T08,'HDFC Bank, Malleshwaram Branch',
     750000.00,'ACTIVE',NULL,NULL,NULL,NULL,
     0,107),
    -- WF=DRAFT (trust in draft; temple.trust_registered=false)
    (108,0,108,'Sri Gangadhareshwara Cave Temple Trust','KA/BLR/TR/2015/001',
     '2015-09-10','Sub Registrar, Bengaluru Urban','SINGLE_TRUSTEE',
     @PAN_T09,@BANK_T09,'SBI, Gavipuram Branch',
     420000.00,'ACTIVE',NULL,NULL,NULL,NULL,
     0,108),
    -- WF=APPROVED
    (109,0,109,'ISKCON Bangalore Trust','KA/BLR/TR/1997/001',
     '1997-03-22','Sub Registrar, Bengaluru Urban','MULTI_TRUSTEE',
     @PAN_T10,@BANK_T10,'State Bank of India, Rajajinagar Branch',
     12000000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"ISKCON Bangalore Trust","trustType":"MULTI_TRUSTEE","trustRegistrationNumber":"KA/BLR/TR/1997/001","registeringAuthority":"Sub Registrar, Bengaluru Urban"}',
     0,109),
    (110,0,110,'Siddaganga Mutt Charitable Trust','KA/TMK/TR/1956/001',
     '1956-01-26','Sub Registrar, Tumkuru','ENDOWMENT',
     @PAN_T11,@BANK_T11,'Canara Bank, Tumkuru Branch',
     8500000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Siddaganga Mutt Charitable Trust","trustType":"ENDOWMENT","trustRegistrationNumber":"KA/TMK/TR/1956/001","registeringAuthority":"Sub Registrar, Tumkuru"}',
     0,110),
    (111,0,111,'Sri Siddaroodha Swami Charitable Trust','KA/DWD/TR/1908/001',
     '1908-10-08','Sub Registrar, Dharwad','MULTI_TRUSTEE',
     @PAN_T12,@BANK_T12,'State Bank of India, Dharwad Branch',
     3200000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Sri Siddaroodha Swami Charitable Trust","trustType":"MULTI_TRUSTEE","trustRegistrationNumber":"KA/DWD/TR/1908/001","registeringAuthority":"Sub Registrar, Dharwad"}',
     0,111),
    (112,0,112,'Keladi Rameshwara Devasthana Trust','KA/SHV/TR/1995/001',
     '1995-02-14','Sub Registrar, Shivamogga','SINGLE_TRUSTEE',
     @PAN_T13,@BANK_T13,'Canara Bank, Keladi Branch',
     920000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Keladi Rameshwara Devasthana Trust","trustType":"SINGLE_TRUSTEE","trustRegistrationNumber":"KA/SHV/TR/1995/001","registeringAuthority":"Sub Registrar, Shivamogga"}',
     0,112),
    -- T15: trust APPROVED (temple SUSPENDED)
    (113,0,114,'Sharana Basaveshwara Devasthana Trust','KA/KLB/TR/1988/001',
     '1988-05-20','Sub Registrar, Kalaburagi','MULTI_TRUSTEE',
     @PAN_T15,@BANK_T15,'State Bank of India, Kalaburagi Branch',
     2100000.00,'ACTIVE',NULL,NULL,'SYSTEM_VERIFIED',
     '{"trustName":"Sharana Basaveshwara Devasthana Trust","trustType":"MULTI_TRUSTEE","trustRegistrationNumber":"KA/KLB/TR/1988/001","registeringAuthority":"Sub Registrar, Kalaburagi"}',
     0,114),
    -- T19: trust SUBMITTED (temple.trust_registered=false)
    (114,0,118,'Sri Balagangadharanatha Temple Trust','KA/BLR/TR/2020/004',
     '2020-11-10','Sub Registrar, Bengaluru Rural','SINGLE_TRUSTEE',
     @PAN_T19,@BANK_T19,'Canara Bank, Nelamangala Branch',
     380000.00,'ACTIVE',NULL,NULL,NULL,NULL,
     0,118),
    -- T20: trust DISSOLVED (ARCHIVED temple)
    (115,0,119,'Kambadahalli Jain Devasthana Trust','KA/MDY/TR/1980/001',
     '1980-12-01','Sub Registrar, Mandya','MULTI_TRUSTEE',
     @PAN_T20,@BANK_T20,'State Bank of India, Nagamangala Branch',
     0.00,'DISSOLVED','2020-06-01','Temple ceased religious operations - Archived',
     NULL,NULL,
     0,119);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 5 — BOARD MEMBERS (ids 200-231)
-- 2 members per trust. Aadhaar fields: encrypted=NULL, hash=NULL, last4=synthetic.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO board_members
    (id, lock_version, trust_id, full_name, aadhaar_encrypted, aadhaar_hash,
     aadhaar_last4, designation, appointment_date, contact_number,
     is_current, is_verified_by_dc, is_deleted, created_by)
VALUES
    -- Trust 100 (T01)
    (200,0,100,'Krishnaswamy Iyengar',NULL,NULL,'1001','Chairman','2020-04-01','9000010001',1,1,0,100),
    (201,0,100,'Savitha Narasimhan',NULL,NULL,'1002','Secretary','2020-04-01','9000010002',1,1,0,100),
    -- Trust 101 (T02)
    (202,0,101,'Narayana Rao',NULL,NULL,'1003','Chairman','2021-01-15','9000010003',1,1,0,101),
    (203,0,101,'Manjula Devaraja',NULL,NULL,'1004','Treasurer','2021-01-15','9000010004',1,1,0,101),
    -- Trust 102 (T03)
    (204,0,102,'Venkataraman Pillai',NULL,NULL,'1005','Chairman','2019-06-01','9000010005',1,1,0,102),
    (205,0,102,'Padmavathi Srinivasan',NULL,NULL,'1006','Secretary','2019-06-01','9000010006',1,1,0,102),
    -- Trust 103 (T04, SUBMITTED trust)
    (206,0,103,'Hanumanthappa Gowda',NULL,NULL,'1007','Chairman','2022-03-10','9000010007',1,0,0,103),
    (207,0,103,'Shanthamani Shivaswamy',NULL,NULL,'1008','Secretary','2022-03-10','9000010008',1,0,0,103),
    -- Trust 104 (T05)
    (208,0,104,'Ponnappa Coorgi',NULL,NULL,'1009','Chairman','2018-08-15','9000010009',1,1,0,104),
    (209,0,104,'Kavya Thimmaiah',NULL,NULL,'1010','Treasurer','2018-08-15','9000010010',1,1,0,104),
    -- Trust 105 (T06, CLARIFICATION_REQUESTED trust)
    (210,0,105,'Shivakumar Belur',NULL,NULL,'1011','Chairman','2015-07-01','9000010011',1,0,0,105),
    (211,0,105,'Rekha Hoysala',NULL,NULL,'1012','Secretary','2015-07-01','9000010012',1,0,0,105),
    -- Trust 106 (T07)
    (212,0,106,'Ramakrishna Belur',NULL,NULL,'1013','Chairman','2017-04-14','9000010013',1,1,0,106),
    (213,0,106,'Saraswathi Vishwanath',NULL,NULL,'1014','Treasurer','2017-04-14','9000010014',1,1,0,106),
    -- Trust 107 (T08, REJECTED trust)
    (214,0,107,'Malleshwara Reddy',NULL,NULL,'1015','Chairman','2020-01-15','9000010015',1,0,0,107),
    (215,0,107,'Vimala Nagaraj',NULL,NULL,'1016','Secretary','2020-01-15','9000010016',1,0,0,107),
    -- Trust 108 (T09, DRAFT trust)
    (216,0,108,'Ganesha Murthy',NULL,NULL,'1017','Chairman','2023-06-01','9000010017',1,0,0,108),
    (217,0,108,'Lalitha Krishnamurthy',NULL,NULL,'1018','Secretary','2023-06-01','9000010018',1,0,0,108),
    -- Trust 109 (T10)
    (218,0,109,'Madhu Pandit Das',NULL,NULL,'1019','Chairman','2010-03-22','9000010019',1,1,0,109),
    (219,0,109,'Bhakti Caitanya Swami',NULL,NULL,'1020','Secretary','2010-03-22','9000010020',1,1,0,109),
    -- Trust 110 (T11)
    (220,0,110,'Nirmalanandanatha Swami',NULL,NULL,'1021','Chairman','2000-01-26','9000010021',1,1,0,110),
    (221,0,110,'Chandrakanth Prasad',NULL,NULL,'1022','Treasurer','2000-01-26','9000010022',1,1,0,110),
    -- Trust 111 (T12)
    (222,0,111,'Virupaksha Das',NULL,NULL,'1023','Chairman','2005-10-08','9000010023',1,1,0,111),
    (223,0,111,'Shantadevi Kulkarni',NULL,NULL,'1024','Secretary','2005-10-08','9000010024',1,1,0,111),
    -- Trust 112 (T13)
    (224,0,112,'Parameshwara Bhat',NULL,NULL,'1025','Chairman','2010-02-14','9000010025',1,1,0,112),
    (225,0,112,'Vijayalakshmi Nair',NULL,NULL,'1026','Secretary','2010-02-14','9000010026',1,1,0,112),
    -- Trust 113 (T15, SUSPENDED temple)
    (226,0,113,'Basavaraja Patil',NULL,NULL,'1027','Chairman','2016-05-20','9000010027',1,1,0,114),
    (227,0,113,'Sunitha Desai',NULL,NULL,'1028','Secretary','2016-05-20','9000010028',1,1,0,114),
    -- Trust 114 (T19, SUBMITTED trust)
    (228,0,114,'Srikanth Naidu',NULL,NULL,'1029','Chairman','2023-11-10','9000010029',1,0,0,118),
    (229,0,114,'Deepa Ramaiah',NULL,NULL,'1030','Secretary','2023-11-10','9000010030',1,0,0,118),
    -- Trust 115 (T20, DISSOLVED trust)
    (230,0,115,'Chandraprakash Jain',NULL,NULL,'1031','Chairman','2000-12-01','9000010031',0,1,0,119),
    (231,0,115,'Manorama Jain',NULL,NULL,'1032','Secretary','2000-12-01','9000010032',0,1,0,119);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 6 — TRUST FINANCIALS (ids 200-210)
-- One FY 2024-25 record per approved/dissolved trust.
-- uk_trust_financials_trust_fy_deleted ensures one active row per (trust,FY).
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO trust_financials
    (id, trust_id, financial_year, annual_income, annual_expenditure,
     submitted_at, is_deleted, created_by)
VALUES
    (200,100,'2024-25',9500000.00,4200000.00,'2025-01-15',0,100),
    (201,101,'2024-25',3500000.00,1800000.00,'2025-01-20',0,101),
    (202,102,'2024-25',4200000.00,2100000.00,'2025-02-01',0,102),
    (203,104,'2024-25', 850000.00, 420000.00,'2025-02-10',0,104),
    (204,106,'2024-25',1600000.00, 850000.00,'2025-01-28',0,106),
    (205,109,'2024-25',12000000.00,5500000.00,'2025-02-15',0,109),
    (206,110,'2024-25',8500000.00,3200000.00,'2025-01-10',0,110),
    (207,111,'2024-25',3200000.00,1600000.00,'2025-02-05',0,111),
    (208,112,'2024-25', 920000.00, 480000.00,'2025-01-25',0,112),
    (209,113,'2024-25',2100000.00,1050000.00,'2025-01-30',0,114),
    (210,115,'2023-24',  180000.00, 90000.00,'2024-04-01',0,119);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 7 — ASSET DECLARATIONS (ids 100-118)
-- 19 rows covering all DeclarationStatus values.
-- FY 2024-25: completed cycle. FY 2025-26: current/in-progress.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO asset_declarations
    (id, lock_version, temple_id, district_id, financial_year, version_number,
     status, annual_income, annual_expenditure, gold_grams, buildings_sqft,
     due_date, submitted_at, submitted_by, reviewed_at, reviewed_by,
     acknowledgement_number, acknowledged_at,
     clarification_round, is_overdue, overdue_flagged_at,
     physical_verification_status,
     is_deleted, created_by)
VALUES
    -- T01: 2024-25 APPROVED
    (100,0,100,1,'2024-25',1,'APPROVED',
     95000000.00,42000000.00,15000.000,250000.00,
     '2025-01-31','2024-11-01',100,'2024-11-20',2,
     'ACK/2024-25/MYS/0001','2024-11-20',
     0,0,NULL,NULL,0,100),
    -- T02: 2024-25 APPROVED
    (101,0,101,1,'2024-25',1,'APPROVED',
     35000000.00,16000000.00,8000.000,120000.00,
     '2025-01-31','2024-11-01',101,'2024-11-20',2,
     'ACK/2024-25/MYS/0002','2024-11-20',
     0,0,NULL,NULL,0,101),
    -- T03: 2024-25 APPROVED
    (102,0,102,2,'2024-25',1,'APPROVED',
     42000000.00,19000000.00,9500.000,180000.00,
     '2025-01-31','2024-12-01',102,'2024-12-15',120,
     'ACK/2024-25/MDY/0001','2024-12-15',
     0,0,NULL,NULL,0,102),
    -- T04: 2024-25 OVERDUE (submitted but deadline passed, never reviewed)
    (103,0,103,3,'2024-25',1,'OVERDUE',
     NULL,NULL,NULL,NULL,
     '2025-01-31','2024-10-15',103,NULL,NULL,
     NULL,NULL,
     0,1,'2025-02-01',NULL,0,103),
    -- T05: 2025-26 UNDER_REVIEW
    (104,0,104,4,'2025-26',1,'UNDER_REVIEW',
     8500000.00,3800000.00,NULL,NULL,
     '2026-03-31','2026-01-10',104,'2026-01-20',122,
     NULL,NULL,
     0,0,NULL,NULL,0,104),
    -- T06: 2025-26 CLARIFICATION_REQUIRED
    (105,0,105,5,'2025-26',1,'CLARIFICATION_REQUIRED',
     28000000.00,12000000.00,NULL,NULL,
     '2026-03-31','2026-03-01',105,NULL,NULL,
     NULL,NULL,
     1,0,NULL,NULL,0,105),
    -- T07: 2025-26 SITE_VISIT_SCHEDULED
    (106,0,106,5,'2025-26',1,'SITE_VISIT_SCHEDULED',
     16000000.00,7500000.00,NULL,NULL,
     '2026-03-31','2026-01-15',106,'2026-02-01',123,
     NULL,NULL,
     0,0,NULL,'ORDERED_FOR_PHYSICAL_VERIFICATION',0,106),
    -- T08: 2025-26 SITE_VISIT_COMPLETED
    (107,0,107,6,'2025-26',1,'SITE_VISIT_COMPLETED',
     7500000.00,3200000.00,NULL,NULL,
     '2026-03-31','2026-01-15',107,'2026-03-10',7,
     NULL,NULL,
     0,0,NULL,'PHYSICALLY_VERIFIED',0,107),
    -- T09: 2025-26 SUBMITTED
    (108,0,108,6,'2025-26',1,'SUBMITTED',
     4200000.00,1900000.00,NULL,NULL,
     '2026-03-31','2026-05-10',108,NULL,NULL,
     NULL,NULL,
     0,0,NULL,NULL,0,108),
    -- T10: 2025-26 VERIFIED
    (109,0,109,6,'2025-26',1,'VERIFIED',
     120000000.00,55000000.00,NULL,NULL,
     '2026-03-31','2025-12-01',109,'2026-03-01',7,
     NULL,NULL,
     0,0,NULL,'PHYSICALLY_VERIFIED',0,109),
    -- T11: 2024-25 v1 SUPERSEDED
    (110,0,110,9,'2024-25',1,'SUPERSEDED',
     80000000.00,35000000.00,NULL,NULL,
     '2025-01-31','2024-11-10',110,NULL,NULL,
     NULL,NULL,
     0,0,NULL,NULL,0,110),
    -- T11: 2024-25 v2 APPROVED
    (111,0,110,9,'2024-25',2,'APPROVED',
     85000000.00,38000000.00,12000.000,200000.00,
     '2025-01-31','2024-12-01',110,'2024-12-20',126,
     'ACK/2024-25/TMK/0001','2024-12-20',
     0,0,NULL,NULL,0,110),
    -- T12: 2024-25 REJECTED
    (112,0,111,17,'2024-25',1,'REJECTED',
     32000000.00,14000000.00,NULL,NULL,
     '2025-01-31','2025-01-01',111,'2025-01-20',134,
     NULL,NULL,
     0,0,NULL,NULL,0,111),
    -- T12: 2025-26 DRAFT (new after rejection)
    (113,0,111,17,'2025-26',1,'DRAFT',
     NULL,NULL,NULL,NULL,
     '2026-03-31',NULL,NULL,NULL,NULL,
     NULL,NULL,
     0,0,NULL,NULL,0,111),
    -- T14: 2025-26 DRAFT
    (114,0,113,19,'2025-26',1,'DRAFT',
     NULL,NULL,NULL,NULL,
     '2026-03-31',NULL,NULL,NULL,NULL,
     NULL,NULL,
     0,0,NULL,NULL,0,113),
    -- T15: 2024-25 APPROVED (last before SUSPENSION)
    (115,0,114,11,'2024-25',1,'APPROVED',
     21000000.00,9500000.00,4500.000,80000.00,
     '2025-01-31','2024-09-01',114,'2024-09-15',128,
     'ACK/2024-25/KLB/0001','2024-09-15',
     0,0,NULL,NULL,0,114),
    -- T16: 2025-26 WITHDRAWN
    (116,0,115,20,'2025-26',1,'WITHDRAWN',
     NULL,NULL,NULL,NULL,
     '2026-03-31','2025-12-01',115,NULL,NULL,
     NULL,NULL,
     0,0,NULL,NULL,0,115),
    -- T19: 2025-26 v1 REJECTED
    (117,0,118,7,'2025-26',1,'REJECTED',
     3800000.00,1700000.00,NULL,NULL,
     '2026-03-31','2026-01-10',118,'2026-02-10',124,
     NULL,NULL,
     0,0,NULL,NULL,0,118),
    -- T19: 2025-26 v2 SUBMITTED (new after v1 rejection)
    (118,0,118,7,'2025-26',2,'SUBMITTED',
     3900000.00,1750000.00,NULL,NULL,
     '2026-03-31','2026-03-15',118,NULL,NULL,
     NULL,NULL,
     0,0,NULL,NULL,0,118);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 8 — DECLARATION CLARIFICATIONS
-- One outbound thread for T06 (CLARIFICATION_REQUIRED).
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO declaration_clarifications
    (id, declaration_id, direction, message, author_id, created_at)
VALUES
    (100,105,'OUTBOUND',
     'Please provide supporting documents for the gold ornament inventory listed under movable assets. The weight (15,000 grams) requires itemised invoices or temple records.',
     123,'2026-04-05 10:30:00');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 9 — TEMPLE PROFILE STAGING (ids 100-113)
-- Covers APPROVED / SUBMITTED / UPDATED_AFTER_APPROVAL / REJECTED /
--        SUPERSEDED / RE_APPROVED / DRAFT staging scenarios.
-- UNIQUE KEY uk_profile_staging_temple_version (temple_id, version).
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO temple_profile_staging
    (id, temple_id, status, version, version_number, lock_version,
     phone, email, website, contact_person_name, contact_person_designation,
     bank_name, bank_account_number_encrypted, bank_ifsc,
     languages_of_worship, description,
     reviewed_at, reviewed_by,
     is_deleted, created_by)
VALUES
    -- T01: APPROVED profile (v1)
    (100,100,'APPROVED',1,1,0,
     '0821-2401234','chamundeshwari@templeregistry.dev','https://chamundeshwari.com',
     'Executive Officer','Temple Authority',
     'State Bank of India',@PROF_BANK_T01,'SBIN0040001',
     'Kannada,Sanskrit','Sri Chamundeshwari Temple atop Chamundi Hills, Mysuru. One of the 18 Maha Shakti Peethas.',
     '2024-11-15',2,0,100),
    -- T02: SUBMITTED (first submission, pending DC review)
    (101,101,'SUBMITTED',1,1,0,
     '08221-225566','nanjundeshwara@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada,Sanskrit',NULL,
     NULL,NULL,0,101),
    -- T03: UPDATED_AFTER_APPROVAL (approved profile, TA currently editing)
    (102,102,'UPDATED_AFTER_APPROVAL',1,1,0,
     '08232-252525','ranganathaswamy@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada,Tamil',NULL,
     '2024-12-20',120,0,102),
    -- T05: APPROVED profile
    (103,104,'APPROVED',1,1,0,
     '08272-228800','omkareshwara@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada,Kodava','Sri Omkareshwara Temple on Madikeri island.',
     '2025-06-01',122,0,104),
    -- T06: APPROVED profile (profile OK; trust has separate clarification)
    (104,105,'APPROVED',1,1,0,
     '08177-273113','hoysaleshwara@templeregistry.dev','https://hoysaleshwara.in',
     'Executive Officer','Temple Authority',
     NULL,@PROF_BANK_T06,NULL,
     'Kannada','Hoysaleshwara Temple — finest example of Hoysala architecture.',
     '2026-03-15',123,0,105),
    -- T07: APPROVED profile
    (105,106,'APPROVED',1,1,0,
     '08177-268023','chennakesava@templeregistry.dev','https://chennakesava-belur.in',
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada,Sanskrit','Sri Chennakesava Temple, Belur — UNESCO listed.',
     '2026-03-20',123,0,106),
    -- T08: REJECTED profile
    (106,107,'REJECTED',1,1,0,
     '080-23569999','kadu.malleshwara@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada',NULL,
     '2026-02-15',7,0,107),
    -- T10: APPROVED profile
    (107,109,'APPROVED',1,1,0,
     '080-23471956','iskcon.blr@templeregistry.dev','https://iskconbangalore.org',
     'Temple President','Temple Authority',
     NULL,NULL,NULL,
     'English,Kannada,Sanskrit','ISKCON Sri Radha Krishnachandra Temple, largest ISKCON temple in Karnataka.',
     '2026-01-10',7,0,109),
    -- T11: v1 SUPERSEDED (old version)
    (108,110,'SUPERSEDED',1,1,0,
     '0816-2225566','siddaganga@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada',NULL,
     '2025-03-01',126,0,110),
    -- T12: APPROVED profile
    (109,111,'APPROVED',1,1,0,
     '0836-2441620','siddaroodha@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada','Sri Siddaroodha Swami Temple, Hubli-Dharwad.',
     '2025-08-15',134,0,111),
    -- T13: APPROVED profile
    (110,112,'APPROVED',1,1,0,
     '08182-261212','keladi@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada','Sri Keladi Rameshwara Temple — Nayaka-era heritage site.',
     '2025-10-01',135,0,112),
    -- T15: APPROVED profile (before temple SUSPENSION)
    (111,114,'APPROVED',1,1,0,
     '08472-268555','basaveshwara@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada','Sri Sharana Basaveshwara Temple, Kalaburagi.',
     '2025-04-01',128,0,114),
    -- T17: DRAFT profile (TA started but not submitted)
    (112,116,'DRAFT',1,1,0,
     '08482-225566','nanak.jhira@templeregistry.dev',NULL,
     'Temple Manager','Temple Authority',
     NULL,NULL,NULL,
     'Punjabi,Kannada',NULL,
     NULL,NULL,0,116),
    -- T11: v2 RE_APPROVED profile (current)
    (113,110,'RE_APPROVED',2,2,0,
     '0816-2225567','siddaganga.mutt@templeregistry.dev','https://siddagangamutt.org',
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada,Sanskrit','Sri Siddaganga Mutt Temple — seat of the Lingayat Pontiff since 14th century.',
     '2025-05-15',126,0,110);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 10 — TEMPLE PROFILE CURRENT (ids 100-109)
-- One row per temple with an APPROVED or RE_APPROVED profile.
-- T03 row reflects the profile approved BEFORE the ongoing edit (UPDATED_AFTER_APPROVAL).
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO temple_profile_current
    (id, temple_id, phone, email, website,
     contact_person_name, contact_person_designation,
     bank_name, bank_account_number_encrypted, bank_ifsc,
     languages_of_worship, description,
     published_at, published_by)
VALUES
    -- T01: current approved profile
    (100,100,'0821-2401234','chamundeshwari@templeregistry.dev','https://chamundeshwari.com',
     'Executive Officer','Temple Authority',
     'State Bank of India',@PROF_BANK_T01,'SBIN0040001',
     'Kannada,Sanskrit','Sri Chamundeshwari Temple atop Chamundi Hills, Mysuru. One of the 18 Maha Shakti Peethas.',
     '2024-11-15',2),
    -- T03: profile from before TA began editing (UPDATED_AFTER_APPROVAL)
    (101,102,'08232-252525','ranganathaswamy@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,@PROF_BANK_T03,NULL,
     'Kannada,Tamil','Sri Ranganathaswamy Temple, Srirangapatna.',
     '2024-12-20',120),
    -- T05: current approved profile
    (102,104,'08272-228800','omkareshwara@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada,Kodava','Sri Omkareshwara Temple on Madikeri island.',
     '2025-06-01',122),
    -- T06: current approved profile
    (103,105,'08177-273113','hoysaleshwara@templeregistry.dev','https://hoysaleshwara.in',
     'Executive Officer','Temple Authority',
     NULL,@PROF_BANK_T06,NULL,
     'Kannada','Hoysaleshwara Temple — finest example of Hoysala architecture.',
     '2026-03-15',123),
    -- T07: current approved profile
    (104,106,'08177-268023','chennakesava@templeregistry.dev','https://chennakesava-belur.in',
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada,Sanskrit','Sri Chennakesava Temple, Belur — UNESCO listed.',
     '2026-03-20',123),
    -- T10: current approved profile
    (105,109,'080-23471956','iskcon.blr@templeregistry.dev','https://iskconbangalore.org',
     'Temple President','Temple Authority',
     NULL,NULL,NULL,
     'English,Kannada,Sanskrit','ISKCON Sri Radha Krishnachandra Temple, largest ISKCON temple in Karnataka.',
     '2026-01-10',7),
    -- T11: current RE_APPROVED profile (v2)
    (106,110,'0816-2225567','siddaganga.mutt@templeregistry.dev','https://siddagangamutt.org',
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada,Sanskrit','Sri Siddaganga Mutt Temple — seat of the Lingayat Pontiff since 14th century.',
     '2025-05-15',126),
    -- T12: current approved profile
    (107,111,'0836-2441620','siddaroodha@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada','Sri Siddaroodha Swami Temple, Hubli-Dharwad.',
     '2025-08-15',134),
    -- T13: current approved profile
    (108,112,'08182-261212','keladi@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada','Sri Keladi Rameshwara Temple — Nayaka-era heritage site.',
     '2025-10-01',135),
    -- T15: current approved profile (before suspension)
    (109,114,'08472-268555','basaveshwara@templeregistry.dev',NULL,
     'Executive Officer','Temple Authority',
     NULL,NULL,NULL,
     'Kannada','Sri Sharana Basaveshwara Temple, Kalaburagi.',
     '2025-04-01',128);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 11 — WORKFLOW INSTANCES (ids 200-253)
-- 16 TRUST + 19 DECLARATION + 14 PROFILE = 49 instances.
-- current_actor_role follows GovernanceStatusResolverImpl.actionableByFor().
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO workflow_instances
    (id, entity_type, entity_id, status, sub_status, lock_version, version_number,
     current_actor_role, created_by_user_id, temple_id, district_id,
     submitted_at, status_updated_at, is_deleted, created_by)
VALUES
    -- ── TRUST WORKFLOW INSTANCES ──────────────────────────────────────────────
    (200,'TRUST',100,'APPROVED',  NULL,0,2,NULL,100,100,1, '2024-11-15','2024-11-25',0,100),
    (201,'TRUST',101,'APPROVED',  NULL,0,2,NULL,101,101,1, '2024-11-15','2024-11-25',0,101),
    (202,'TRUST',102,'APPROVED',  NULL,0,2,NULL,102,102,2, '2024-12-01','2024-12-15',0,102),
    (203,'TRUST',103,'SUBMITTED', NULL,0,1,'DC', 103,103,3, '2025-04-10','2025-04-10',0,103),
    (204,'TRUST',104,'APPROVED',  NULL,0,2,NULL,104,104,4, '2024-10-01','2024-10-20',0,104),
    (205,'TRUST',105,'CLARIFICATION_REQUESTED',NULL,0,2,'TA',105,105,5,'2025-06-01','2025-07-10',0,105),
    (206,'TRUST',106,'APPROVED',  NULL,0,2,NULL,106,106,5, '2024-09-01','2024-09-20',0,106),
    (207,'TRUST',107,'REJECTED',  NULL,0,2,'TA',107,107,6, '2025-02-01','2025-02-28',0,107),
    (208,'TRUST',108,'DRAFT',     NULL,0,1,NULL,108,108,6, NULL,NULL,0,108),
    (209,'TRUST',109,'APPROVED',  NULL,0,2,NULL,109,109,6, '2023-06-01','2023-06-20',0,109),
    (210,'TRUST',110,'APPROVED',  NULL,0,2,NULL,110,110,9, '2023-04-01','2023-04-15',0,110),
    (211,'TRUST',111,'APPROVED',  NULL,0,2,NULL,111,111,17,'2023-09-01','2023-09-20',0,111),
    (212,'TRUST',112,'APPROVED',  NULL,0,2,NULL,112,112,18,'2024-01-15','2024-01-30',0,112),
    (213,'TRUST',113,'APPROVED',  NULL,0,2,NULL,114,114,11,'2024-03-01','2024-03-20',0,114),
    (214,'TRUST',114,'SUBMITTED', NULL,0,1,'DC',118,118,7, '2025-12-15','2025-12-15',0,118),
    (215,'TRUST',115,'APPROVED',  NULL,0,2,NULL,119,119,2, '2015-03-01','2015-03-20',0,119),

    -- ── DECLARATION WORKFLOW INSTANCES ────────────────────────────────────────
    (220,'DECLARATION',100,'APPROVED',NULL,0,2,NULL,100,100,1,'2024-11-01','2024-11-20',0,100),
    (221,'DECLARATION',101,'APPROVED',NULL,0,2,NULL,101,101,1,'2024-11-01','2024-11-20',0,101),
    (222,'DECLARATION',102,'APPROVED',NULL,0,2,NULL,102,102,2,'2024-12-01','2024-12-15',0,102),
    (223,'DECLARATION',103,'OVERDUE', NULL,0,1,'SYSTEM',103,103,3,'2024-10-15','2025-02-01',0,103),
    (224,'DECLARATION',104,'UNDER_REVIEW',NULL,0,2,'DC',104,104,4,'2026-01-10','2026-01-20',0,104),
    (225,'DECLARATION',105,'CLARIFICATION_REQUESTED',NULL,0,2,'TA',105,105,5,'2026-03-01','2026-04-05',0,105),
    (226,'DECLARATION',106,'UNDER_REVIEW','SITE_VISIT_SCHEDULED',0,2,'DC',106,106,5,'2026-01-15','2026-02-01',0,106),
    (227,'DECLARATION',107,'UNDER_REVIEW','SITE_VISIT_COMPLETED',0,2,'DC',107,107,6,'2026-01-15','2026-03-10',0,107),
    (228,'DECLARATION',108,'SUBMITTED', NULL,0,1,'DC',108,108,6,'2026-05-10','2026-05-10',0,108),
    (229,'DECLARATION',109,'UNDER_REVIEW','VERIFIED',0,2,'DC',109,109,6,'2025-12-01','2026-03-01',0,109),
    (230,'DECLARATION',110,'SUPERSEDED',NULL,0,2,NULL,110,110,9,'2024-11-10','2024-12-01',0,110),
    (231,'DECLARATION',111,'APPROVED', NULL,0,2,NULL,110,110,9,'2024-12-01','2024-12-20',0,110),
    (232,'DECLARATION',112,'REJECTED', NULL,0,2,'TA',111,111,17,'2025-01-01','2025-01-20',0,111),
    (233,'DECLARATION',113,'DRAFT',    NULL,0,1,NULL,111,111,17,NULL,NULL,0,111),
    (234,'DECLARATION',114,'DRAFT',    NULL,0,1,NULL,113,113,19,NULL,NULL,0,113),
    (235,'DECLARATION',115,'APPROVED', NULL,0,2,NULL,114,114,11,'2024-09-01','2024-09-15',0,114),
    (236,'DECLARATION',116,'WITHDRAWN',NULL,0,2,NULL,115,115,20,'2025-12-01','2025-12-20',0,115),
    (237,'DECLARATION',117,'REJECTED', NULL,0,2,'TA',118,118,7,'2026-01-10','2026-02-10',0,118),
    (238,'DECLARATION',118,'SUBMITTED',NULL,0,1,'DC',118,118,7,'2026-03-15','2026-03-15',0,118),

    -- ── TEMPLE PROFILE WORKFLOW INSTANCES ─────────────────────────────────────
    (240,'TEMPLE_PROFILE',100,'APPROVED',  NULL,0,2,NULL,100,100,1,'2024-11-01','2024-11-15',0,100),
    (241,'TEMPLE_PROFILE',101,'SUBMITTED', NULL,0,1,'DC',101,101,1,'2026-04-20','2026-04-20',0,101),
    (242,'TEMPLE_PROFILE',102,'UPDATED_AFTER_APPROVAL',NULL,0,3,'TA',102,102,2,'2024-12-01','2026-04-01',0,102),
    (243,'TEMPLE_PROFILE',103,'APPROVED',  NULL,0,2,NULL,104,104,4,'2025-05-01','2025-06-01',0,104),
    (244,'TEMPLE_PROFILE',104,'APPROVED',  NULL,0,2,NULL,105,105,5,'2026-03-01','2026-03-15',0,105),
    (245,'TEMPLE_PROFILE',105,'APPROVED',  NULL,0,2,NULL,106,106,5,'2026-03-05','2026-03-20',0,106),
    (246,'TEMPLE_PROFILE',106,'REJECTED',  NULL,0,2,'TA',107,107,6,'2026-01-20','2026-02-15',0,107),
    (247,'TEMPLE_PROFILE',107,'APPROVED',  NULL,0,2,NULL,109,109,6,'2025-12-15','2026-01-10',0,109),
    (248,'TEMPLE_PROFILE',108,'SUPERSEDED',NULL,0,2,NULL,110,110,9,'2025-02-01','2025-03-01',0,110),
    (249,'TEMPLE_PROFILE',109,'APPROVED',  NULL,0,2,NULL,111,111,17,'2025-07-01','2025-08-15',0,111),
    (250,'TEMPLE_PROFILE',110,'APPROVED',  NULL,0,2,NULL,112,112,18,'2025-09-01','2025-10-01',0,112),
    (251,'TEMPLE_PROFILE',111,'APPROVED',  NULL,0,2,NULL,114,114,11,'2025-03-01','2025-04-01',0,114),
    (252,'TEMPLE_PROFILE',112,'DRAFT',     NULL,0,1,NULL,116,116,12,NULL,NULL,0,116),
    (253,'TEMPLE_PROFILE',113,'RE_APPROVED',NULL,0,3,NULL,110,110,9,'2025-04-01','2025-05-15',0,110);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 12 — WORKFLOW TRANSITIONS (ids 300+)
-- Key transitions only: SUBMIT + final DC action per workflow instance.
-- actor_id: TA users = 100-119 · DC users: district-1=2, d-2=120, d-3=121,
--   d-4=122, d-5=123, d-6=7, d-7=124, d-9=126, d-11=128, d-12=129,
--   d-13=130, d-17=134, d-18=135, d-19=136, d-20=137.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO workflow_transitions
    (id, workflow_instance_id, from_status, to_status, action,
     actor_id, actor_role, comment, instance_version_at_transition, performed_at,
     is_deleted, created_by)
VALUES
-- ── TRUST TRANSITIONS ─────────────────────────────────────────────────────────
(300,200,NULL,        'SUBMITTED','SUBMIT',              100,'TEMPLE_AUTHORITY',NULL,1,'2024-11-15',0,1),
(301,200,'SUBMITTED', 'APPROVED', 'APPROVE',               2,'DISTRICT_COLLECTOR',NULL,2,'2024-11-25',0,1),
(302,201,NULL,        'SUBMITTED','SUBMIT',              101,'TEMPLE_AUTHORITY',NULL,1,'2024-11-15',0,1),
(303,201,'SUBMITTED', 'APPROVED', 'APPROVE',               2,'DISTRICT_COLLECTOR',NULL,2,'2024-11-25',0,1),
(304,202,NULL,        'SUBMITTED','SUBMIT',              102,'TEMPLE_AUTHORITY',NULL,1,'2024-12-01',0,1),
(305,202,'SUBMITTED', 'APPROVED', 'APPROVE',             120,'DISTRICT_COLLECTOR',NULL,2,'2024-12-15',0,1),
(306,203,NULL,        'SUBMITTED','SUBMIT',              103,'TEMPLE_AUTHORITY',NULL,1,'2025-04-10',0,1),
(307,204,NULL,        'SUBMITTED','SUBMIT',              104,'TEMPLE_AUTHORITY',NULL,1,'2024-10-01',0,1),
(308,204,'SUBMITTED', 'APPROVED', 'APPROVE',             122,'DISTRICT_COLLECTOR',NULL,2,'2024-10-20',0,1),
(309,205,NULL,        'SUBMITTED','SUBMIT',              105,'TEMPLE_AUTHORITY',NULL,1,'2025-06-01',0,1),
(310,205,'SUBMITTED', 'CLARIFICATION_REQUESTED','REQUEST_CLARIFICATION',123,'DISTRICT_COLLECTOR','Please provide updated PAN card copy.',2,'2025-07-10',0,1),
(311,206,NULL,        'SUBMITTED','SUBMIT',              106,'TEMPLE_AUTHORITY',NULL,1,'2024-09-01',0,1),
(312,206,'SUBMITTED', 'APPROVED', 'APPROVE',             123,'DISTRICT_COLLECTOR',NULL,2,'2024-09-20',0,1),
(313,207,NULL,        'SUBMITTED','SUBMIT',              107,'TEMPLE_AUTHORITY',NULL,1,'2025-02-01',0,1),
(314,207,'SUBMITTED', 'REJECTED', 'REJECT',                7,'DISTRICT_COLLECTOR','Trust registration documents are incomplete and unverifiable.',2,'2025-02-28',0,1),
(315,209,NULL,        'SUBMITTED','SUBMIT',              109,'TEMPLE_AUTHORITY',NULL,1,'2023-06-01',0,1),
(316,209,'SUBMITTED', 'APPROVED', 'APPROVE',               7,'DISTRICT_COLLECTOR',NULL,2,'2023-06-20',0,1),
(317,210,NULL,        'SUBMITTED','SUBMIT',              110,'TEMPLE_AUTHORITY',NULL,1,'2023-04-01',0,1),
(318,210,'SUBMITTED', 'APPROVED', 'APPROVE',             126,'DISTRICT_COLLECTOR',NULL,2,'2023-04-15',0,1),
(319,211,NULL,        'SUBMITTED','SUBMIT',              111,'TEMPLE_AUTHORITY',NULL,1,'2023-09-01',0,1),
(320,211,'SUBMITTED', 'APPROVED', 'APPROVE',             134,'DISTRICT_COLLECTOR',NULL,2,'2023-09-20',0,1),
(321,212,NULL,        'SUBMITTED','SUBMIT',              112,'TEMPLE_AUTHORITY',NULL,1,'2024-01-15',0,1),
(322,212,'SUBMITTED', 'APPROVED', 'APPROVE',             135,'DISTRICT_COLLECTOR',NULL,2,'2024-01-30',0,1),
(323,213,NULL,        'SUBMITTED','SUBMIT',              114,'TEMPLE_AUTHORITY',NULL,1,'2024-03-01',0,1),
(324,213,'SUBMITTED', 'APPROVED', 'APPROVE',             128,'DISTRICT_COLLECTOR',NULL,2,'2024-03-20',0,1),
(325,214,NULL,        'SUBMITTED','SUBMIT',              118,'TEMPLE_AUTHORITY',NULL,1,'2025-12-15',0,1),
(326,215,NULL,        'SUBMITTED','SUBMIT',              119,'TEMPLE_AUTHORITY',NULL,1,'2015-03-01',0,1),
(327,215,'SUBMITTED', 'APPROVED', 'APPROVE',             120,'DISTRICT_COLLECTOR',NULL,2,'2015-03-20',0,1),

-- ── DECLARATION TRANSITIONS ────────────────────────────────────────────────────
(330,220,NULL,       'SUBMITTED','SUBMIT',100,'TEMPLE_AUTHORITY',NULL,1,'2024-11-01',0,1),
(331,220,'SUBMITTED','APPROVED', 'APPROVE',2,'DISTRICT_COLLECTOR',NULL,2,'2024-11-20',0,1),
(332,221,NULL,       'SUBMITTED','SUBMIT',101,'TEMPLE_AUTHORITY',NULL,1,'2024-11-01',0,1),
(333,221,'SUBMITTED','APPROVED', 'APPROVE',2,'DISTRICT_COLLECTOR',NULL,2,'2024-11-20',0,1),
(334,222,NULL,       'SUBMITTED','SUBMIT',102,'TEMPLE_AUTHORITY',NULL,1,'2024-12-01',0,1),
(335,222,'SUBMITTED','APPROVED', 'APPROVE',120,'DISTRICT_COLLECTOR',NULL,2,'2024-12-15',0,1),
(336,223,NULL,       'SUBMITTED','SUBMIT',103,'TEMPLE_AUTHORITY',NULL,1,'2024-10-15',0,1),
-- OVERDUE is set by system scheduler; no DC action transition
(337,224,NULL,       'SUBMITTED','SUBMIT',104,'TEMPLE_AUTHORITY',NULL,1,'2026-01-10',0,1),
(338,224,'SUBMITTED','UNDER_REVIEW','BEGIN_REVIEW',122,'DISTRICT_COLLECTOR',NULL,2,'2026-01-20',0,1),
(339,225,NULL,       'SUBMITTED','SUBMIT',105,'TEMPLE_AUTHORITY',NULL,1,'2026-03-01',0,1),
(340,225,'SUBMITTED','CLARIFICATION_REQUESTED','REQUEST_CLARIFICATION',123,'DISTRICT_COLLECTOR','Please provide itemised gold ornament inventory documents.',2,'2026-04-05',0,1),
(341,226,NULL,       'SUBMITTED','SUBMIT',106,'TEMPLE_AUTHORITY',NULL,1,'2026-01-15',0,1),
(342,226,'SUBMITTED','UNDER_REVIEW','BEGIN_REVIEW',123,'DISTRICT_COLLECTOR',NULL,2,'2026-02-01',0,1),
(343,227,NULL,       'SUBMITTED','SUBMIT',107,'TEMPLE_AUTHORITY',NULL,1,'2026-01-15',0,1),
(344,227,'SUBMITTED','UNDER_REVIEW','BEGIN_REVIEW',7,'DISTRICT_COLLECTOR',NULL,2,'2026-01-25',0,1),
(345,228,NULL,       'SUBMITTED','SUBMIT',108,'TEMPLE_AUTHORITY',NULL,1,'2026-05-10',0,1),
(346,229,NULL,       'SUBMITTED','SUBMIT',109,'TEMPLE_AUTHORITY',NULL,1,'2025-12-01',0,1),
(347,229,'SUBMITTED','UNDER_REVIEW','BEGIN_REVIEW',7,'DISTRICT_COLLECTOR',NULL,2,'2025-12-10',0,1),
-- T11 v1 superseded
(348,230,NULL,       'SUBMITTED','SUBMIT',110,'TEMPLE_AUTHORITY',NULL,1,'2024-11-10',0,1),
(349,230,'SUBMITTED','SUPERSEDED','APPROVE',126,'DISTRICT_COLLECTOR','v2 approved; v1 superseded.',2,'2024-12-20',0,1),
-- T11 v2 approved
(350,231,NULL,       'SUBMITTED','SUBMIT',110,'TEMPLE_AUTHORITY',NULL,1,'2024-12-01',0,1),
(351,231,'SUBMITTED','APPROVED', 'APPROVE',126,'DISTRICT_COLLECTOR',NULL,2,'2024-12-20',0,1),
-- T12 rejected
(352,232,NULL,       'SUBMITTED','SUBMIT',111,'TEMPLE_AUTHORITY',NULL,1,'2025-01-01',0,1),
(353,232,'SUBMITTED','REJECTED', 'REJECT',134,'DISTRICT_COLLECTOR','Significant discrepancy in reported income vs audited accounts.',2,'2025-01-20',0,1),
-- T15 approved
(354,235,NULL,       'SUBMITTED','SUBMIT',114,'TEMPLE_AUTHORITY',NULL,1,'2024-09-01',0,1),
(355,235,'SUBMITTED','APPROVED', 'APPROVE',128,'DISTRICT_COLLECTOR',NULL,2,'2024-09-15',0,1),
-- T16 withdrawn
(356,236,NULL,       'SUBMITTED','SUBMIT',115,'TEMPLE_AUTHORITY',NULL,1,'2025-12-01',0,1),
(357,236,'SUBMITTED','WITHDRAWN','WITHDRAW',115,'TEMPLE_AUTHORITY','Temple undergoing major renovation; withdrawing for this cycle.',2,'2025-12-20',0,1),
-- T19 v1 rejected
(358,237,NULL,       'SUBMITTED','SUBMIT',118,'TEMPLE_AUTHORITY',NULL,1,'2026-01-10',0,1),
(359,237,'SUBMITTED','REJECTED', 'REJECT',124,'DISTRICT_COLLECTOR','Supporting documents for land assets are missing.',2,'2026-02-10',0,1),
-- T19 v2 submitted
(360,238,NULL,       'SUBMITTED','SUBMIT',118,'TEMPLE_AUTHORITY',NULL,1,'2026-03-15',0,1),

-- ── PROFILE STAGING TRANSITIONS ────────────────────────────────────────────────
(370,240,NULL,       'SUBMITTED','SUBMIT',100,'TEMPLE_AUTHORITY',NULL,1,'2024-11-01',0,1),
(371,240,'SUBMITTED','APPROVED', 'APPROVE',2,'DISTRICT_COLLECTOR',NULL,2,'2024-11-15',0,1),
(372,241,NULL,       'SUBMITTED','SUBMIT',101,'TEMPLE_AUTHORITY',NULL,1,'2026-04-20',0,1),
(373,242,NULL,       'SUBMITTED','SUBMIT',102,'TEMPLE_AUTHORITY',NULL,1,'2024-12-01',0,1),
(374,242,'SUBMITTED','APPROVED', 'APPROVE',120,'DISTRICT_COLLECTOR',NULL,2,'2024-12-20',0,1),
(375,242,'APPROVED', 'UPDATED_AFTER_APPROVAL','EDIT_APPROVED',102,'TEMPLE_AUTHORITY',NULL,3,'2026-04-01',0,1),
(376,243,NULL,       'SUBMITTED','SUBMIT',104,'TEMPLE_AUTHORITY',NULL,1,'2025-05-01',0,1),
(377,243,'SUBMITTED','APPROVED', 'APPROVE',122,'DISTRICT_COLLECTOR',NULL,2,'2025-06-01',0,1),
(378,244,NULL,       'SUBMITTED','SUBMIT',105,'TEMPLE_AUTHORITY',NULL,1,'2026-03-01',0,1),
(379,244,'SUBMITTED','APPROVED', 'APPROVE',123,'DISTRICT_COLLECTOR',NULL,2,'2026-03-15',0,1),
(380,245,NULL,       'SUBMITTED','SUBMIT',106,'TEMPLE_AUTHORITY',NULL,1,'2026-03-05',0,1),
(381,245,'SUBMITTED','APPROVED', 'APPROVE',123,'DISTRICT_COLLECTOR',NULL,2,'2026-03-20',0,1),
(382,246,NULL,       'SUBMITTED','SUBMIT',107,'TEMPLE_AUTHORITY',NULL,1,'2026-01-20',0,1),
(383,246,'SUBMITTED','REJECTED', 'REJECT',7,'DISTRICT_COLLECTOR','Contact details are inconsistent with official records.',2,'2026-02-15',0,1),
(384,247,NULL,       'SUBMITTED','SUBMIT',109,'TEMPLE_AUTHORITY',NULL,1,'2025-12-15',0,1),
(385,247,'SUBMITTED','APPROVED', 'APPROVE',7,'DISTRICT_COLLECTOR',NULL,2,'2026-01-10',0,1),
-- T11 v1 staging (SUPERSEDED)
(386,248,NULL,       'SUBMITTED','SUBMIT',110,'TEMPLE_AUTHORITY',NULL,1,'2025-02-01',0,1),
(387,248,'SUBMITTED','APPROVED', 'APPROVE',126,'DISTRICT_COLLECTOR',NULL,2,'2025-03-01',0,1),
(388,248,'APPROVED', 'SUPERSEDED','RE_APPROVE',126,'DISTRICT_COLLECTOR',NULL,3,'2025-05-15',0,1),
-- T12 profile
(389,249,NULL,       'SUBMITTED','SUBMIT',111,'TEMPLE_AUTHORITY',NULL,1,'2025-07-01',0,1),
(390,249,'SUBMITTED','APPROVED', 'APPROVE',134,'DISTRICT_COLLECTOR',NULL,2,'2025-08-15',0,1),
-- T13 profile
(391,250,NULL,       'SUBMITTED','SUBMIT',112,'TEMPLE_AUTHORITY',NULL,1,'2025-09-01',0,1),
(392,250,'SUBMITTED','APPROVED', 'APPROVE',135,'DISTRICT_COLLECTOR',NULL,2,'2025-10-01',0,1),
-- T15 profile
(393,251,NULL,       'SUBMITTED','SUBMIT',114,'TEMPLE_AUTHORITY',NULL,1,'2025-03-01',0,1),
(394,251,'SUBMITTED','APPROVED', 'APPROVE',128,'DISTRICT_COLLECTOR',NULL,2,'2025-04-01',0,1),
-- T11 v2 staging (RE_APPROVED)
(395,253,NULL,       'SUBMITTED','SUBMIT',110,'TEMPLE_AUTHORITY',NULL,1,'2025-04-01',0,1),
(396,253,'SUBMITTED','RE_APPROVED','RE_APPROVE',126,'DISTRICT_COLLECTOR',NULL,2,'2025-05-15',0,1);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 13 — ACKNOWLEDGEMENT SEQUENCES
-- Insert-only; AUTO_INCREMENT seq_id. 5 rows for 5 APPROVED declarations.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO acknowledgement_sequences (seq_id, financial_year) VALUES
    (1,'2024-25'),
    (2,'2024-25'),
    (3,'2024-25'),
    (4,'2024-25'),
    (5,'2024-25');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 14 — TEMPLE SEARCH SUMMARY (ids 100-119)
-- Pre-computed materialised view. Refresh via POST /admin/search-summary/rebuild
-- after migration if live computed values are needed.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT IGNORE INTO temple_search_summary
    (id, temple_id, name, registration_number, grade, primary_deity, tradition,
     hobli_id, taluk_id, district_id, city_id,
     temple_status, trust_registered, asset_declaration_status, year_established,
     pending_declarations, overdue_declarations, pending_profile_review,
     has_active_trust, has_approved_declaration,
     last_declaration_at, last_profile_update_at)
VALUES
    -- T01: Grade A · SHAKTA · ACTIVE · APPROVED decl · trust_registered=1
    (100,100,'Sri Chamundeshwari Temple','KA-MYS-0001','A','Chamundeshwari','SHAKTA',
     1,1,1,1,'ACTIVE',1,'APPROVED',1659,0,0,0,1,1,'2024-11-01','2024-11-15'),
    -- T02: Grade A · SHAIVITE · ACTIVE · APPROVED decl · pending profile
    (101,101,'Sri Nanjundeshwara Temple','KA-MYS-0002','A','Nanjundeshwara','SHAIVITE',
     2,1,1,1,'ACTIVE',1,'APPROVED',1143,0,0,1,1,1,'2024-11-01','2026-04-20'),
    -- T03: Grade A · VAISHNAVITE · ACTIVE · APPROVED decl · trust=1
    (102,102,'Sri Ranganathaswamy Temple','KA-MDY-0001','A','Ranganathaswamy','VAISHNAVITE',
     5,4,2,1,'ACTIVE',1,'APPROVED',894,0,0,0,1,1,'2024-12-01','2024-12-20'),
    -- T04: Grade A · SHAIVITE · ACTIVE · OVERDUE decl · no approved trust
    (103,103,'Sri Mahadeshwara Temple','KA-CJN-0001','A','Mahadeshwara','SHAIVITE',
     7,7,3,1,'ACTIVE',0,'OVERDUE',1310,1,1,0,1,0,'2024-10-15',NULL),
    -- T05: Grade B · SHAIVITE · ACTIVE · UNDER_REVIEW decl · trust=1
    (104,104,'Sri Omkareshwara Temple','KA-KDG-0001','B','Omkareshwara','SHAIVITE',
     8,9,4,1,'ACTIVE',1,'UNDER_REVIEW',1820,1,0,0,1,0,'2026-01-10','2025-06-01'),
    -- T06: Grade A · SHAIVITE · ACTIVE · CLARIFICATION_REQUIRED decl · trust=1
    (105,105,'Hoysaleshwara Temple','KA-HSN-0001','A','Hoysaleshwara','SHAIVITE',
     9,11,5,1,'ACTIVE',1,'CLARIFICATION_REQUIRED',1121,1,0,0,1,0,'2026-03-01','2026-03-15'),
    -- T07: Grade B · VAISHNAVITE · ACTIVE · SITE_VISIT_SCHEDULED decl · trust=1
    (106,106,'Sri Chennakesava Temple','KA-HSN-0002','B','Chennakesava','VAISHNAVITE',
     9,12,5,1,'ACTIVE',1,'SITE_VISIT_SCHEDULED',1117,1,0,0,1,0,'2026-01-15','2026-03-20'),
    -- T08: Grade B · SHAIVITE · ACTIVE · SITE_VISIT_COMPLETED decl · trust rejected
    (107,107,'Sri Kadu Malleshwara Temple','KA-BLR-0001','B','Kadu Malleshwara','SHAIVITE',
     10,13,6,2,'ACTIVE',0,'SITE_VISIT_COMPLETED',1800,1,0,0,1,0,'2026-01-15','2026-02-15'),
    -- T09: Grade B · SHAIVITE · ACTIVE · SUBMITTED decl · trust draft
    (108,108,'Sri Gangadhareshwara Cave Temple','KA-BLR-0002','B','Gangadhareshwara','SHAIVITE',
     11,14,6,2,'ACTIVE',0,'SUBMITTED',1537,1,0,0,1,0,'2026-05-10',NULL),
    -- T10: Grade A · VAISHNAVITE · ACTIVE · VERIFIED decl · trust=1
    (109,109,'ISKCON Sri Radha Krishnachandra Temple','KA-BLR-0003','A','Radha Krishnachandra','VAISHNAVITE',
     10,13,6,2,'ACTIVE',1,'VERIFIED',1997,1,0,0,1,0,'2025-12-01','2026-01-10'),
    -- T11: Grade A · SHAIVITE · ACTIVE · APPROVED decl (v2) · trust=1
    (110,110,'Sri Siddaganga Mutt Temple','KA-TMK-0001','A','Siddagangaiah Swami','SHAIVITE',
     12,16,9,2,'ACTIVE',1,'APPROVED',1399,0,0,0,1,1,'2024-12-01','2025-05-15'),
    -- T12: Grade B · SHAIVITE · ACTIVE · DRAFT decl (after rejection) · trust=1
    (111,111,'Sri Siddaroodha Swami Temple','KA-DWD-0001','B','Siddaroodha Swami','SHAIVITE',
     13,18,17,4,'ACTIVE',1,'DRAFT',1907,0,0,0,1,0,'2025-01-01','2025-08-15'),
    -- T13: Grade B · SHAIVITE · ACTIVE · no declaration · trust=1
    (112,112,'Sri Keladi Rameshwara Temple','KA-SHV-0001','B','Rameshwara','SHAIVITE',
     14,20,18,5,'ACTIVE',1,NULL,1580,0,0,0,1,0,NULL,'2025-10-01'),
    -- T14: Grade C · SHAIVITE · ACTIVE · DRAFT decl · no trust
    (113,113,'Sri Tarakeshwara Temple','KA-DVG-0001','C','Tarakeshwara','SHAIVITE',
     NULL,NULL,19,5,'ACTIVE',0,'DRAFT',1380,0,0,0,0,0,NULL,NULL),
    -- T15: Grade B · SHAIVITE · SUSPENDED · APPROVED decl · trust=1
    (114,114,'Sri Sharana Basaveshwara Temple','KA-KLB-0001','B','Sharana Basaveshwara','SHAIVITE',
     NULL,NULL,11,3,'SUSPENDED',1,'APPROVED',1649,0,0,0,1,1,'2024-09-01','2025-04-01'),
    -- T16: Grade C · SHAKTA · ACTIVE · WITHDRAWN decl · no trust
    (115,115,'Sri Ucchangi Bhairaveshwara Temple','KA-CTD-0001','C','Bhairaveshwara','SHAKTA',
     NULL,NULL,20,5,'ACTIVE',0,'WITHDRAWN',1050,0,0,0,0,0,'2025-12-01',NULL),
    -- T17: Grade B · OTHER · ACTIVE · no declaration · no trust (Gurudwara)
    (116,116,'Sri Gurudwara Nanak Jhira Sahib','KA-BDR-0001','B','Guru Nanak','OTHER',
     NULL,NULL,12,3,'ACTIVE',0,NULL,1499,0,0,0,0,0,NULL,NULL),
    -- T18: Grade C · SHAIVITE · FROZEN · no declaration · no trust
    (117,117,'Sri Manavi Veerbhadreshwara Temple','KA-RCR-0001','C','Veerbhadreshwara','SHAIVITE',
     NULL,NULL,13,3,'FROZEN',0,NULL,1200,0,0,0,0,0,NULL,NULL),
    -- T19: Grade C · SHAIVITE · ACTIVE · SUBMITTED decl (v2) · trust SUBMITTED
    (118,118,'Sri Balagangadharanatha Temple','KA-BLR-0004','C','Balagangadharanatha','SHAIVITE',
     NULL,NULL,7,2,'ACTIVE',0,'SUBMITTED',1760,1,0,0,1,0,'2026-03-15',NULL),
    -- T20: Grade C · JAIN · ARCHIVED · no declaration · dissolved trust
    (119,119,'Sri Kambadahalli Bahubali Temple','KA-MDY-0002','C','Bahubali','JAIN',
     6,5,2,1,'ARCHIVED',1,NULL,900,0,0,0,0,0,NULL,NULL);


SET FOREIGN_KEY_CHECKS = 1;
